
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 39;
  public static final int FUNCTION = 31;
  public static final int CHAR = 22;
  public static final int CASE = 54;
  public static final int DIFERENTE = 7;
  public static final int INTEGER = 19;
  public static final int PUNTOCOMA = 38;
  public static final int ENDLOOP = 51;
  public static final int FOR = 26;
  public static final int WRITE = 45;
  public static final int NOT = 14;
  public static final int MENORIGUAL = 11;
  public static final int AND = 12;
  public static final int ENDSWITCH = 57;
  public static final int MAYORQUE = 9;
  public static final int IGUAL = 6;
  public static final int IN = 15;
  public static final int OR = 13;
  public static final int DIV = 17;
  public static final int BEGIN = 28;
  public static final int NUM = 47;
  public static final int LOOP = 50;
  public static final int IF = 23;
  public static final int T_CHAR = 44;
  public static final int ID = 48;
  public static final int MAYORIGUAL = 10;
  public static final int PARIZQ = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 32;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int PROGRAM = 30;
  public static final int COMA = 36;
  public static final int MENOS = 3;
  public static final int MOD = 16;
  public static final int BREAK = 55;
  public static final int SWITCH = 53;
  public static final int ASIGNACION = 35;
  public static final int T_STRING = 49;
  public static final int MENORQUE = 8;
  public static final int ENDIF = 52;
  public static final int ELSE = 24;
  public static final int PUNTO = 37;
  public static final int READ = 46;
  public static final int TO = 27;
  public static final int WHILE = 25;
  public static final int DEFAULT = 56;
  public static final int FLOAT = 21;
  public static final int END = 33;
  public static final int NUMFLOAT = 58;
  public static final int STRING = 20;
  public static final int FALSE = 43;
  public static final int PARDER = 41;
  public static final int DIVISION = 5;
  public static final int VAR = 34;
  public static final int PROCEDURE = 29;
  public static final int MULTIPLICACION = 4;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "DIFERENTE",
  "MENORQUE",
  "MAYORQUE",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "NOT",
  "IN",
  "MOD",
  "DIV",
  "BOOLEAN",
  "INTEGER",
  "STRING",
  "FLOAT",
  "CHAR",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "TO",
  "BEGIN",
  "PROCEDURE",
  "PROGRAM",
  "FUNCTION",
  "RETURN",
  "END",
  "VAR",
  "ASIGNACION",
  "COMA",
  "PUNTO",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "PARIZQ",
  "PARDER",
  "TRUE",
  "FALSE",
  "T_CHAR",
  "WRITE",
  "READ",
  "NUM",
  "ID",
  "T_STRING",
  "LOOP",
  "ENDLOOP",
  "ENDIF",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "ENDSWITCH",
  "NUMFLOAT"
  };
}

